//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMLightFramework.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.192:7047/DynamicsNAV110/WS/ERPSPEZ/Page/ExcelTemplateAgedAccount" +
            "sPayable")]
        public string MVVMLightFramework_WebService_ExcelTemplateAgedAccountsPayable_Service {
            get {
                return ((string)(this["MVVMLightFramework_WebService_ExcelTemplateAgedAccountsPayable_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.192:7047/DynamicsNAV110/WS/ERPSPEZ/Page/Power_BI_Aged_Inventory_" +
            "Chart")]
        public string MVVMLightFramework_WebService_Power_BI_Aged_Inventory_Chart_Service {
            get {
                return ((string)(this["MVVMLightFramework_WebService_Power_BI_Aged_Inventory_Chart_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.192:7047/DynamicsNAV110/WS/ERPSPEZ/Page/powerbifinance")]
        public string MVVMLightFramework_WebService_powerbifinance_Service {
            get {
                return ((string)(this["MVVMLightFramework_WebService_powerbifinance_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.192:7047/DynamicsNAV110/WS/ERPSPEZ/Page/ExcelTemplateRetainedEar" +
            "nings")]
        public string MVVMLightFramework_WebService_ExcelTemplateRetainedEarnings_Service {
            get {
                return ((string)(this["MVVMLightFramework_WebService_ExcelTemplateRetainedEarnings_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.192:7047/DynamicsNAV110/WS/ERPSPEZ/Page/Power_BI_Vertriebspipeli" +
            "ne")]
        public string MVVMLightFramework_WebService_Power_BI_Vertriebspipeline_Service {
            get {
                return ((string)(this["MVVMLightFramework_WebService_Power_BI_Vertriebspipeline_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.192:7047/DynamicsNAV110/WS/ERPSPEZ/Page/Power_BI_Arbeitsdatumber" +
            "ech")]
        public string MVVMLightFramework_WebService_Power_BI_Arbeitsdatumberech_Service {
            get {
                return ((string)(this["MVVMLightFramework_WebService_Power_BI_Arbeitsdatumberech_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.192:7047/DynamicsNAV110/WS/ERPSPEZ/Page/Power_BI_Budgetvergleich" +
            "_Projektpreis")]
        public string MVVMLightFramework_WebService_Power_BI_Budgetvergleich_Projektpreis_Service {
            get {
                return ((string)(this["MVVMLightFramework_WebService_Power_BI_Budgetvergleich_Projektpreis_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.192:7047/DynamicsNAV110/WS/ERPSPEZ/Page/ExcelTemplateViewCompany" +
            "Information")]
        public string MVVMLightFramework_WebService_ExcelTemplateViewCompanyInformation_Service {
            get {
                return ((string)(this["MVVMLightFramework_WebService_ExcelTemplateViewCompanyInformation_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.192:7047/DynamicsNAV110/WS/ERPSPEZ/Page/Power_BI_Aged_Acc_Payabl" +
            "e")]
        public string MVVMLightFramework_WebService_Power_BI_Aged_Acc_Payable_Service {
            get {
                return ((string)(this["MVVMLightFramework_WebService_Power_BI_Aged_Acc_Payable_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.192:7047/DynamicsNAV110/WS/ERPSPEZ/Page/workflowPurchaseDocument" +
            "Lines")]
        public string MVVMLightFramework_WebService_workflowPurchaseDocumentLines_Service {
            get {
                return ((string)(this["MVVMLightFramework_WebService_workflowPurchaseDocumentLines_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.192:7047/DynamicsNAV110/WS/ERPSPEZ/Page/ExcelTemplateTrialBalanc" +
            "e")]
        public string MVVMLightFramework_WebService_ExcelTemplateTrialBalance_Service {
            get {
                return ((string)(this["MVVMLightFramework_WebService_ExcelTemplateTrialBalance_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.192:7047/DynamicsNAV110/WS/ERPSPEZ/Page/workflowSalesDocumentLin" +
            "es")]
        public string MVVMLightFramework_WebService_workflowSalesDocumentLines_Service {
            get {
                return ((string)(this["MVVMLightFramework_WebService_workflowSalesDocumentLines_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.192:7047/DynamicsNAV110/WS/ERPSPEZ/Page/SalesOrder")]
        public string MVVMLightFramework_WebService_SalesOrder_Service {
            get {
                return ((string)(this["MVVMLightFramework_WebService_SalesOrder_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.192:7047/DynamicsNAV110/WS/ERPSPEZ/Page/ExcelTemplateBalanceShee" +
            "t")]
        public string MVVMLightFramework_WebService_ExcelTemplateBalanceSheet_Service {
            get {
                return ((string)(this["MVVMLightFramework_WebService_ExcelTemplateBalanceSheet_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.192:7047/DynamicsNAV110/WS/ERPSPEZ/Page/AccountantPortalActivity" +
            "Cues")]
        public string MVVMLightFramework_WebService_AccountantPortalActivityCues_Service {
            get {
                return ((string)(this["MVVMLightFramework_WebService_AccountantPortalActivityCues_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.192:7047/DynamicsNAV110/WS/ERPSPEZ/Page/workflowPurchaseDocument" +
            "s")]
        public string MVVMLightFramework_WebService_workflowPurchaseDocuments_Service {
            get {
                return ((string)(this["MVVMLightFramework_WebService_workflowPurchaseDocuments_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.192:7047/DynamicsNAV110/WS/ERPSPEZ/Page/workflowGenJournalBatche" +
            "s")]
        public string MVVMLightFramework_WebService_workflowGenJournalBatches_Service {
            get {
                return ((string)(this["MVVMLightFramework_WebService_workflowGenJournalBatches_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.192:7047/DynamicsNAV110/WS/ERPSPEZ/Page/AccountantPortalFinanceC" +
            "ues")]
        public string MVVMLightFramework_WebService_AccountantPortalFinanceCues_Service {
            get {
                return ((string)(this["MVVMLightFramework_WebService_AccountantPortalFinanceCues_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.192:7047/DynamicsNAV110/WS/ERPSPEZ/Page/Chart_of_Accounts")]
        public string MVVMLightFramework_WebService_Chart_of_Accounts_Service {
            get {
                return ((string)(this["MVVMLightFramework_WebService_Chart_of_Accounts_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.192:7047/DynamicsNAV110/WS/ERPSPEZ/Page/workflowSalesDocuments")]
        public string MVVMLightFramework_WebService_workflowSalesDocuments_Service {
            get {
                return ((string)(this["MVVMLightFramework_WebService_workflowSalesDocuments_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.192:7047/DynamicsNAV110/WS/ERPSPEZ/Page/Power_BI_Aged_Acc_Receiv" +
            "able")]
        public string MVVMLightFramework_WebService_Power_BI_Aged_Acc_Receivable_Service {
            get {
                return ((string)(this["MVVMLightFramework_WebService_Power_BI_Aged_Acc_Receivable_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.192:7047/DynamicsNAV110/WS/ERPSPEZ/Page/purchaseDocumentLines")]
        public string MVVMLightFramework_WebService_purchaseDocumentLines_Service {
            get {
                return ((string)(this["MVVMLightFramework_WebService_purchaseDocumentLines_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.192:7047/DynamicsNAV110/WS/ERPSPEZ/Page/Power_BI_Lagerr%C3%BCckb" +
            "lickdiagramm")]
        public string MVVMLightFramework_WebService_Power_BI_Lagerrückblickdiagramm_Service {
            get {
                return ((string)(this["MVVMLightFramework_WebService_Power_BI_Lagerrückblickdiagramm_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.192:7047/DynamicsNAV110/WS/ERPSPEZ/Page/workflowWebhookSubscript" +
            "ions")]
        public string MVVMLightFramework_WebService_workflowWebhookSubscriptions_Service {
            get {
                return ((string)(this["MVVMLightFramework_WebService_workflowWebhookSubscriptions_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.192:7047/DynamicsNAV110/WS/ERPSPEZ/Page/Power_BI_Debitor_Saldenr" +
            "%C3%BCckblick")]
        public string MVVMLightFramework_WebService_Power_BI_Debitor_Saldenrückblick_Service {
            get {
                return ((string)(this["MVVMLightFramework_WebService_Power_BI_Debitor_Saldenrückblick_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.192:7047/DynamicsNAV110/WS/ERPSPEZ/Page/UserTaskSetComplete")]
        public string MVVMLightFramework_WebService_UserTaskSetComplete_Service {
            get {
                return ((string)(this["MVVMLightFramework_WebService_UserTaskSetComplete_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.192:7047/DynamicsNAV110/WS/ERPSPEZ/Page/workflowVendors")]
        public string MVVMLightFramework_WebService_workflowVendors_Service {
            get {
                return ((string)(this["MVVMLightFramework_WebService_workflowVendors_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.192:7047/DynamicsNAV110/WS/ERPSPEZ/Page/Projektaufgabenzeilen")]
        public string MVVMLightFramework_WebService_Projektaufgabenzeilen_Service {
            get {
                return ((string)(this["MVVMLightFramework_WebService_Projektaufgabenzeilen_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.192:7047/DynamicsNAV110/WS/ERPSPEZ/Page/SPS")]
        public string MVVMLightFramework_WebService_SPS_Service {
            get {
                return ((string)(this["MVVMLightFramework_WebService_SPS_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.192:7047/DynamicsNAV110/WS/ERPSPEZ/Page/Projektplanzeilen")]
        public string MVVMLightFramework_WebService_Projektplanzeilen_Service {
            get {
                return ((string)(this["MVVMLightFramework_WebService_Projektplanzeilen_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.192:7047/DynamicsNAV110/WS/ERPSPEZ/Page/workflowCustomers")]
        public string MVVMLightFramework_WebService_workflowCustomers_Service {
            get {
                return ((string)(this["MVVMLightFramework_WebService_workflowCustomers_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.192:7047/DynamicsNAV110/WS/ERPSPEZ/Page/ExcelTemplateAgedAccount" +
            "sReceivable")]
        public string MVVMLightFramework_WebService_ExcelTemplateAgedAccountsReceivable_Service {
            get {
                return ((string)(this["MVVMLightFramework_WebService_ExcelTemplateAgedAccountsReceivable_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.192:7047/DynamicsNAV110/WS/ERPSPEZ/Page/Job_Planning_Lines")]
        public string MVVMLightFramework_WebService_Job_Planning_Lines_Service {
            get {
                return ((string)(this["MVVMLightFramework_WebService_Job_Planning_Lines_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.192:7047/DynamicsNAV110/WS/ERPSPEZ/Page/Power_BI_Job_Act_v_Budg_" +
            "Cost")]
        public string MVVMLightFramework_WebService_Power_BI_Job_Act_v_Budg_Cost_Service {
            get {
                return ((string)(this["MVVMLightFramework_WebService_Power_BI_Job_Act_v_Budg_Cost_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.192:7047/DynamicsNAV110/WS/ERPSPEZ/SystemService")]
        public string MVVMLightFramework_WebService_SystemService {
            get {
                return ((string)(this["MVVMLightFramework_WebService_SystemService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.192:7047/DynamicsNAV110/WS/ERPSPEZ/Page/Power_BI_Projektrentabil" +
            "it%C3%A4t")]
        public string MVVMLightFramework_WebService_Power_BI_Projektrentabilität_Service {
            get {
                return ((string)(this["MVVMLightFramework_WebService_Power_BI_Projektrentabilität_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.192:7047/DynamicsNAV110/WS/ERPSPEZ/Codeunit/WorkflowActionRespon" +
            "se")]
        public string MVVMLightFramework_WebService_WorkflowActionResponse {
            get {
                return ((string)(this["MVVMLightFramework_WebService_WorkflowActionResponse"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.192:7047/DynamicsNAV110/WS/ERPSPEZ/Page/ExcelTemplateCashFlowSta" +
            "tement")]
        public string MVVMLightFramework_WebService_ExcelTemplateCashFlowStatement_Service {
            get {
                return ((string)(this["MVVMLightFramework_WebService_ExcelTemplateCashFlowStatement_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.192:7047/DynamicsNAV110/WS/ERPSPEZ/Page/Power_BI_Top_5_Verkaufsc" +
            "hancen")]
        public string MVVMLightFramework_WebService_Power_BI_Top_5_Verkaufschancen_Service {
            get {
                return ((string)(this["MVVMLightFramework_WebService_Power_BI_Top_5_Verkaufschancen_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:7047/DynamicsNAV110/WS/ERPSPEZ/Page/Power_BI_Sales_Pipeline")]
        public string MVVMLightFramework_WebService_Power_BI_Sales_Pipeline_Service {
            get {
                return ((string)(this["MVVMLightFramework_WebService_Power_BI_Sales_Pipeline_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.192:7047/DynamicsNAV110/WS/ERPSPEZ/Page/Power_BI_Job_Profitabili" +
            "ty")]
        public string MVVMLightFramework_WebService_Power_BI_Job_Profitability_Service {
            get {
                return ((string)(this["MVVMLightFramework_WebService_Power_BI_Job_Profitability_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.192:7047/DynamicsNAV110/WS/ERPSPEZ/Page/salesDocuments")]
        public string MVVMLightFramework_WebService_salesDocuments_Service {
            get {
                return ((string)(this["MVVMLightFramework_WebService_salesDocuments_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.192:7047/DynamicsNAV110/WS/ERPSPEZ/Page/workflowGenJournalLines")]
        public string MVVMLightFramework_WebService_workflowGenJournalLines_Service {
            get {
                return ((string)(this["MVVMLightFramework_WebService_workflowGenJournalLines_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.192:7047/DynamicsNAV110/WS/ERPSPEZ/Page/Power_BI_Kreditor_Salden" +
            "r%C3%BCckblick")]
        public string MVVMLightFramework_WebService_Power_BI_Kreditor_Saldenrückblick_Service {
            get {
                return ((string)(this["MVVMLightFramework_WebService_Power_BI_Kreditor_Saldenrückblick_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.192:7047/DynamicsNAV110/WS/ERPSPEZ/Page/Kontenplan")]
        public string MVVMLightFramework_WebService_Kontenplan_Service {
            get {
                return ((string)(this["MVVMLightFramework_WebService_Kontenplan_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.192:7047/DynamicsNAV110/WS/ERPSPEZ/Page/AccountantPortalUserTask" +
            "s")]
        public string MVVMLightFramework_WebService_AccountantPortalUserTasks_Service {
            get {
                return ((string)(this["MVVMLightFramework_WebService_AccountantPortalUserTasks_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.192:7047/DynamicsNAV110/WS/ERPSPEZ/Page/Projekt%C3%BCbersicht")]
        public string MVVMLightFramework_WebService_Projektübersicht_Service {
            get {
                return ((string)(this["MVVMLightFramework_WebService_Projektübersicht_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.192:7047/DynamicsNAV110/WS/ERPSPEZ/Page/Power_BI_Budgetvergleich" +
            "_Projektkosten")]
        public string MVVMLightFramework_WebService_Power_BI_Budgetvergleich_Projektkosten_Service {
            get {
                return ((string)(this["MVVMLightFramework_WebService_Power_BI_Budgetvergleich_Projektkosten_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.192:7047/DynamicsNAV110/WS/ERPSPEZ/Page/ExcelTemplateIncomeState" +
            "ment")]
        public string MVVMLightFramework_WebService_ExcelTemplateIncomeStatement_Service {
            get {
                return ((string)(this["MVVMLightFramework_WebService_ExcelTemplateIncomeStatement_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.192:7047/DynamicsNAV110/WS/ERPSPEZ/Page/Power_BI_WorkDate_Calc")]
        public string MVVMLightFramework_WebService_Power_BI_WorkDate_Calc_Service {
            get {
                return ((string)(this["MVVMLightFramework_WebService_Power_BI_WorkDate_Calc_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.192:7047/DynamicsNAV110/WS/ERPSPEZ/Page/Job_Task_Lines")]
        public string MVVMLightFramework_WebService_Job_Task_Lines_Service {
            get {
                return ((string)(this["MVVMLightFramework_WebService_Job_Task_Lines_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.192:7047/DynamicsNAV110/WS/ERPSPEZ/Page/Power_BI_Job_Act_v_Budg_" +
            "Price")]
        public string MVVMLightFramework_WebService_Power_BI_Job_Act_v_Budg_Price_Service {
            get {
                return ((string)(this["MVVMLightFramework_WebService_Power_BI_Job_Act_v_Budg_Price_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.192:7047/DynamicsNAV110/WS/ERPSPEZ/Page/Power_BI_Top_5_Opportuni" +
            "ties")]
        public string MVVMLightFramework_WebService_Power_BI_Top_5_Opportunities_Service {
            get {
                return ((string)(this["MVVMLightFramework_WebService_Power_BI_Top_5_Opportunities_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.192:7047/DynamicsNAV110/WS/ERPSPEZ/Page/Job_List")]
        public string MVVMLightFramework_WebService_Job_List_Service {
            get {
                return ((string)(this["MVVMLightFramework_WebService_Job_List_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.192:7047/DynamicsNAV110/WS/ERPSPEZ/Page/workflowItems")]
        public string MVVMLightFramework_WebService_workflowItems_Service {
            get {
                return ((string)(this["MVVMLightFramework_WebService_workflowItems_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.192:7047/DynamicsNAV110/WS/ERPSPEZ/Page/purchaseDocuments")]
        public string MVVMLightFramework_WebService_purchaseDocuments_Service {
            get {
                return ((string)(this["MVVMLightFramework_WebService_purchaseDocuments_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.192:7047/DynamicsNAV110/WS/ERPSPEZ/Page/Customer")]
        public string MVVMLightFramework_WebService_Customer_Service {
            get {
                return ((string)(this["MVVMLightFramework_WebService_Customer_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.192:7047/DynamicsNAV110/WS/ERPSPEZ/Page/salesDocumentLines")]
        public string MVVMLightFramework_WebService_salesDocumentLines_Service {
            get {
                return ((string)(this["MVVMLightFramework_WebService_salesDocumentLines_Service"]));
            }
        }
    }
}
